@MY_TOKEN_NAME = my_token_value


###

@uuid = verse


###

GET {{NEXT_PUBLIC_API_URL}}/verse HTTP/1.1
Accept: application/json
Content-Type: application/json


### 

# @name delete verse

DELETE {{NEXT_PUBLIC_API_URL}}/verse?isAll=true HTTP/1.1
Accept: application/json
Content-Type: application/json


### 

# @name get App version

GET {{NEXT_PUBLIC_API_URL}}/version HTTP/1.1
Accept: application/json
Content-Type: application/json


### 

# @name Add App version

POST {{NEXT_PUBLIC_API_URL}}/version HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "additionalInfo": {
    "estimatedDowntime": "0",
    "rollbackAvailable": false
  },
  "author": "Release Bot",
  "description": [
    "Fix Search input icon",
    "Tynrai Jingrwai page",
    "Song Correction",
    "UI Update"
  ],
  "mandatory": true,
  "minSupportedVersion": "1.0.1",
  "platforms": [
    "ios",
    "android"
  ],
  "releaseDate": "2025-08-011T14:00:00Z",
  "releaseNotesUrl": "https://jyrwaboys-v2.vercel.app/docs/release/kot-jingrwai",
  "title": "Stable Release",
  "version": "1.0.2"
}


### 


###

# @name App user

GET {{NEXT_PUBLIC_API_URL}}/version/user?version={{uuid}} HTTP/1.1
Accept: application/json
Content-Type: application/json
