import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { MainProvider } from "@/components/provider";
import Head from "next/head";
import { Link } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html data-theme="light" lang="en">
      <Head>
        <title>Kot Jingrwai</title>
        <meta
          name="description"
          content="MyApp helps you stay productive, connected, and secure. Available on iOS and Android."
        />
        <meta property="og:title" content="MyApp – Smart Productivity App" />
        <meta
          property="og:description"
          content="Download MyApp today and supercharge your productivity with a seamless, modern experience."
        />
        <meta property="og:image" content="/preview.png" />
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MainProvider>{children}</MainProvider>
      </body>
    </html>
  );
}
